<a href="https://colab.research.google.com/github/cb4github/LsuSciCompBootCamp2020/blob/master/Day_2_numpy_warmup_exer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import print_function
import numpy as np

# Warm-up Exercise for Numpy

#### Create a 1D array of numbers from 0 to 9

- Desired output:

> `[0 1 2 3 4 5 6 7 8 9]`

In [2]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### Convert the above 1D array to a 2D array with 2 rows

- Desired output:

```
> [[0 1 2 3 4]
   [5 6 7 8 9]]
 ```

In [3]:
arr = arr.reshape(2, 5)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### Calculate the square of a 1D vector, then reshape it to a column vector

- Desired output:

```
[0 1 2 3 4]
[ 0  1  4  9 16]
[[ 0]
 [ 1]
 [ 4]
 [ 9]
 [16]]
 ```

In [5]:
a = np.arange(5)
print(a)
a2 = np.square(a)
print(a2)
a2 = a2.reshape(5, 1)
print(a2)

[0 1 2 3 4]
[ 0  1  4  9 16]
[[ 0]
 [ 1]
 [ 4]
 [ 9]
 [16]]


#### Suppose in an experiment, there are two variables x (from 1 to 5) and y (from 2 to 4), using numpy's broadcasting to calculate the matrix of all combinations of `x^2 + y` 

- Desired output:


>
```
[[ 3  4  5]
 [ 6  7  8]
 [11 12 13]
 [18 19 20]
 [27 28 29]]
 ```

In [3]:
x = np.arange(1,6).reshape(-1,1)
print(x)
y = np.arange(2,5)
print(y)
z = x**2 +y
print(z)

[[1]
 [2]
 [3]
 [4]
 [5]]
[2 3 4]
[[ 3  4  5]
 [ 6  7  8]
 [11 12 13]
 [18 19 20]
 [27 28 29]]


#### Sum the rows and columns of the above matrix using Numpy's aggregation function

- Desired output:

> 
```
[65 70 75]
[12 21 36 57 84]
```

In [4]:
row_sum = np.sum(z,axis=0)
print(row_sum)
col_sum = np.sum(z,axis=1)
print(col_sum)

[65 70 75]
[12 21 36 57 84]


#### In Numpy, matrix multiplication is done using the dot() function, verify the matrix multiplication result by writing for loops:

Hint: (you only need to complete the below equation in the nested for loop)

$$cc_{i,j} =\sum_{k=1}^{nca} a_{i,k}b_{k,j} $$

For Matrix multiplication, you can refer to the wiki link to recall the basics:

https://en.wikipedia.org/wiki/Matrix_multiplication#Definition


- Desired output:

```
a=
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b=
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Using numpy's dot function: c=
 [[ 60  70]
 [160 195]]
Verified results using for loop: cc=
 [[ 60  70]
 [160 195]]
 ```

In [5]:
nra = 2
nca = 5
ncb = 2
a = np.arange(nra*nca).reshape(nra,-1)
b = np.arange(nra*nca).reshape(-1,ncb)
print("a=\n",a)
print("b=\n",b)
c = a.dot(b)
print("Using numpy's dot function: c=\n",c)
cc = np.zeros_like(c)

# complete the naive for loop below:
for i in np.arange(nra):
    for j in np.arange(ncb):
        cc[i,j] = 0
        for k in np.arange(nca):
            # TODO: complete this line
            cc[i,j] += a[i,k]*b[k,j]
            pass
print("Verified results using for loop: cc=\n",cc)
print("np.all(c == cc)?", np.all(c == cc))

a=
 [[0 1 2 3 4]
 [5 6 7 8 9]]
b=
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
Using numpy's dot function: c=
 [[ 60  70]
 [160 195]]
Verified results using for loop: cc=
 [[ 60  70]
 [160 195]]
np.all(c == cc)? True


#### Calculate the min, max and mean brain weight and body weight of a dataset

In the demo notebook, we loaded the data from "data.txt" into a numpy array a, The 3 data columns include:
1.  the index,
1.  the brain weight;
1. the body weight.

Index 1-5 (row 1-5) are training set, index 6-9 (row 6-9) are test set

Calculate 

1. min, max and mean brain weight for training set 

2. min, max and mean body weight for test set 


Note that you should ***not*** use a for loop to complete this.

In [6]:
# download the file to local virtual machine
! if [ ! -f "data.txt" ]; then wget 'https://raw.githubusercontent.com/lsuhpchelp/lbrnloniworkshop2019/master/day2_python/data.txt'; else echo 'file exists'; fi;
! cat data.txt # uncomment if you want to take a look at the data
txtfile = 'data.txt'
a = np.loadtxt(txtfile,skiprows=16,usecols={0,1,2},dtype=None,comments="#")
print("\nloaded data:\n", a)

--2020-06-02 18:26:33--  https://raw.githubusercontent.com/lsuhpchelp/lbrnloniworkshop2019/master/day2_python/data.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 630 [text/plain]
Saving to: ‘data.txt’

data.txt            100%[===================>]     630  --.-KB/s    in 0s      

2020-06-02 18:26:33 (38.8 MB/s) - ‘data.txt’ saved [630/630]

#  x01.txt
#    Academic Press, 1991, page 304,
#    ISBN 0-12-656460-4.
#    There are 62 rows of data.  The 3 data columns include:
#      I,  the index,
#      A1, the brain weight;
#      B,  the body weight.
#    We seek a model of the form:
#
#      B = A1 * X1.
#
3 columns
62 rows
Index
Brain Weight
Body Weight
# here is the training set
 1     3.385    44.500 abjhk
 2     0.480    33.38  bc_00asdk
 3     1.350  

In [10]:
train_brain_weight = a[:5,1]
print("training set, brain weight:", train_brain_weight)
train_min_brain_weight = np.min(train_brain_weight) #0 # complete the 3 calcs using numpy's aggregation and slicing
train_max_brain_weight = np.max(train_brain_weight) #0
train_avg_brain_weight = np.mean(train_brain_weight) #0
print("training set, brain weight statistics:")
print("Min=",train_min_brain_weight)
print("Max=",train_max_brain_weight)
print("Mean={:.2f}".format(train_avg_brain_weight))

training set, brain weight: [  3.385   0.48    1.35  465.     36.33 ]
training set, brain weight statistics:
Min= 0.48
Max= 465.0
Mean=101.31


In [13]:
test_body_weight = a[5:,2]
print("test set, body weight:", test_body_weight)
test_min_body_weight = np.min(test_body_weight) #0 # complete the 3 calcs using numpy's aggregation and slicing
test_max_body_weight = np.max(test_body_weight) #0
test_avg_body_weight = np.mean(test_body_weight) #0
print("test set, body weight statistics:")
print("Min=",test_min_body_weight)
print("Max=",test_max_body_weight)
print("Mean={:.2f}".format(test_avg_body_weight))

test set, body weight: [115.   98.2   5.5  58. ]
test set, body weight statistics:
Min= 5.5
Max= 115.0
Mean=69.17
